### ISSUE TITLE
github.com/willdonnelly/passwd is still an indirect dependency of yip after #149

### ISSUE THREAD

**Issue by nianyush** [mudler/yip#154]
https://github.com/mudler/yip/blob/master/go.mod#L81

**Comment by nianyush** [comment]
@mauromorales @mudler should we also refractor [here](https://github.com/mudler/entities/blob/68348bae0f49244e07fe6a8280664361d3a95489/pkg/entities/user.go#L27) to completely remove passwd from yip's dependency?

**Comment by mauromorales** [comment]
@nianyush nice catch, will do

**Comment by mauromorales** [comment]
@mudler please have a look at https://github.com/mudler/entities/pull/13, after it's merged I will bump entities in yip

**Comment by mauromorales** [comment]
merged the bump in yip but we still need a release 

cc @mudler

**Comment by mudler** [comment]
https://github.com/mudler/yip/releases/tag/v1.8.0 published now :+1: , closing! thanks @mauromorales !
